In [ ]:
import numpy as np

In [ ]:
# reshape the array
nums = np.array([1, 2, 3, 4, 5, 6])
# print(nums, nums.shape)

# print(nums.reshape(1, 6)) # 2d
# print(nums.reshape(2, 3))
# print(nums.reshape(3, 2))
# print(nums.reshape(6, 1))
# print(nums.reshape(3, 2, 1))

# # print(nums.reshape(2, 4)) # ValueError
# print(nums.reshape(2, 2)) # ValueError

In [ ]:
# comparison ops -> boolean matrix
nums = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# print(nums > 5)
# print(nums >= 5)
# print(nums < 5)
# print(nums <= 5)
# print(nums != 5)
# print(nums == 5)

# filter the data -> array[condition]
# print(nums[nums > 5])

# even nums
even = (nums % 2 == 0)
print(nums[even])

[2 4 6]


In [ ]:
n1 = [1, 2, 3]
n2 = [4, 5, 6]
print('before', id(n1))
# n1 = [1, 2, 3, 4, 5, 6]
n1.extend(n2)
print('after ', id(n1))
print(n1)

before 6416944128
after  6416944128
[1, 2, 3, 4, 5, 6]


In [ ]:
# stack the data
# horizontal stacking -> 1d
n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])
# [1, 2, 3, 4, 5, 6]
# print(np.hstack([n1, n2, n2, 10, 11, [100, 200]]))

# vertical stack
# print(np.vstack([n1, n2, n2, [10, 11, 12] ])) # 2d

# ArrayManager

In [ ]:
# nums = iter([10, 20, 30])
# print(next(nums))
# print(next(nums))
# print(next(nums))
# print(next(nums))

In [ ]:
# slicing -> (start=0/-1: end+1/end-1: step=1)

# If step is +ve, default start = 0, end+1
# If step is -ve, default start = -1, end-1

nums = np.array([10, 20, 30, 40, 50])
# print(nums)
# print(nums[0], nums[1], nums[2], nums[3], nums[4])
# print(nums[-1], nums[-2], nums[-3], nums[-4], nums[-5])

# print(nums[0:4]) # end + 1 = 4 => end = 3
# print(nums[4:1])
# print(nums[:3])
# print(nums[2:])
# print(nums[2:10])
# print(nums[:])
# print(nums[0:4:2])
# print(nums[0::2])

# print(nums[-3:-5])
# print(nums[-3:-5:-1]) # end-1 = -5 -> end = -5 + 1 = -4
# print(nums[3:5:-1])
# print(nums[-1:1]) # nums[4:1] or nums[-1:-4]
# print(nums[-4:4])
# print(nums[2:-3:1]) # start == end, then []
# print(nums[2:-3:-1]) # start == end, then []
print(nums[:-3:-1])

# print(nums[::1])
# print(nums[::-1]) # reverse

[50 40]


In [ ]:
# name = 'vasanth'
name = ['v', 'a', 's', 'a', 'n', 't', 'h']
print(name[::-1])

['h', 't', 'n', 'a', 's', 'a', 'v']


In [ ]:
# 2d data -> [rows, cols] -> [(start=0/-1: end+1/end-1: step=1), (start=0/-1: end+1/end-1: step=1)]

a = [11, 12, 13, 14, 15, 16, 17, 18]
b = [21, 22, 23, 24, 25, 26, 27, 28]
nums = np.array([a, b])

# print(nums)
# print(nums[0], nums[1])
# print(nums[-1], nums[-2])

# <--- multiple rows ---> # 2d
# print(nums[:])
# print(nums[:1])
# print(nums[-1:])
# print(nums[:-1])

# <---- one row and multiple cols ----> # 1d
# print(nums[0, 1:4])
# print(nums[-1, 2:5])

# <--- multiple rows and multiple cols ---> # 2d
# print(nums[:, 2:7])

[[13 14 15 16 17]
 [23 24 25 26 27]]


In [ ]:
# change the value
nums = np.array([
    [11, 12, 13, 14, 15, 16, 17, 18],
    [21, 22, 23, 24, 25, 26, 27, 28]
])

# nums[:, 2:5] = 100
# print(nums)

# 22, 24, 26, 28 to 50
nums[1, 1::2] = 50
print(nums)

[[11 12 13 14 15 16 17 18]
 [21 50 23 50 25 50 27 50]]


In [ ]:
nums = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 20, 21, 22]
])

# print(nums.shape)

# splitting the data
# vertical splitting
# uniform splitting
# np.vsplit(nums, 3)
# np.vsplit(nums, 3)[0]
# np.vsplit(nums, 3)[1]
# np.vsplit(nums, 3)[2]
# np.vsplit(nums, 2)

# np.vsplit(nums, 4) # ValueError

# custom splitting -> no of pieces = 1 + no of cuts
# np.vsplit(nums, [1, 3])
# np.vsplit(nums, [1, 3])[0]
# np.vsplit(nums, [1, 3])[1]
# np.vsplit(nums, [1, 3])[2]

# np.vsplit(nums, [1, 3, 4])
# np.vsplit(nums, [1, 3, 4])[0]
# np.vsplit(nums, [1, 3, 4])[1]
# np.vsplit(nums, [1, 3, 4])[2]
# np.vsplit(nums, [1, 3, 4])[3]

# np.vsplit(nums, [0, 3])
# np.vsplit(nums, [0, 3])[0]
# np.vsplit(nums, [0, 3])[1]
# np.vsplit(nums, [0, 3])[2]

In [ ]:
# horizontal splitting
# uniform splitting

nums = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])

# np.hsplit(nums, 2)
# np.hsplit(nums, 2)[0]
# np.hsplit(nums, 2)[1]

# np.hsplit(nums, 3) # ValueError

# custom splitting
# np.hsplit(nums, [1, 3])
# np.hsplit(nums, [1, 3])[0]
# np.hsplit(nums, [1, 3])[1]
# np.hsplit(nums, [1, 3])[2]

In [ ]:
# sort the data
# 1d
# nums = np.array([10, 23, 5, 7])
# print(np.sort(nums))

# 2d
nums = np.array([
    [38, 15, 98, 57],
    [63, 19, 56, 77],
    [12, 13, 26, 29]
])

# print(np.sort(nums)) # select a row and sort the cols
# print(np.sort(nums, axis=1)) # same output as above

# print(np.sort(nums, axis=0)) # select a col and sort the rows -> db

In [ ]:
# broadcasting
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# (3, 3)

b = np.array([
    [1, 2, 3]
])
# (1, 3)

# print(a + b) # If only 1 row and no of cols of 2 matrices should match -> broadcast
# print(a - b)
# print(a * b)
# print(a / b)
# print(a // b)
# print(a % b)
# print(a ** b)

In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# (3, 3)

b = np.array([
    [1],
    [2],
    [3]
])
# (1, 3)

# print(a + b) # If only 1 col and rows of both matrices should match -> broadcast

# M*N -> 1*N or M*1 -> broadcast

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [ ]:
# stats
nums = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(np.mean(nums)) # average
print(np.median(nums)) # middle
print(np.std(nums)) # std deviation
print(np.var(nums)) # variance -> square(std deviation)

5.0
5.0
2.581988897471611
6.666666666666667


In [ ]:
# logic of dot product
n1 = [1, 2, 3, 4]
n2 = [1, 2, 3, 4]

def python_product():
    dot = 0
    for i in range(len(n1)):
        dot += n1[i] * n2[i]
    return dot

print(python_product())

n1 = np.array(n1)
n2 = np.array(n2)
print(np.dot(n1, n2))

30
30


In [ ]:
# speed test

from timeit import default_timer as timer

a = np.random.random(1000)
b = np.random.random(1000)

# typecast
list_a = list(a)
list_b = list(b)

def python_product():
    dot = 0
    for i in range(len(list_a)):
        dot += list_a[i] * list_b[i]
    return dot

def numpy_product():
    return np.dot(a, b)

start = timer()
for i in range(10_00_000):
    python_product()
end = timer()
print(f'Python list --> {end - start} secs')

start = timer()
for i in range(10_00_000):
    numpy_product()
end = timer()
print(f'Numpy array --> {end - start} secs')

Python list --> 70.01556475000689 secs
Numpy array --> 0.5783757920144126 secs


In [ ]:
# cons of numpy
# 1. cannot support multiple file formats
# 2. faster upto 5 to 10 lakh

In [ ]:
# PANDAS